citizennet/purescript-ocelot

- src/Blocks/FormControl.purs
- src/Components/Typeahead/Typeahead.purs
- src/Core/Validation.purs
- ui-guide/Components/FormControl.purs
- ui-guide/Components/TextFields.purs
- ui-guide/Components/Validation.purs
This PR fixes our implementation of labels in form controls. Unfortunately, simply wrapping our inputs in the label element to provide an implicit association causes issues due to the fact that [clicking on a label triggers a click event on every element it's associated with](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label), which in the case of our components caused improper behavior (closing the selection container instead of selecting an element, removing elements when clicking the label, etc.)
This means that we have to use the `for` attribute to accomplish the association, which means we need to parameterize our form control block as well as our components by the input id. For now I've done that by adding a `String` parameter to each of the default typeahead …
> Fix Implementation of Labels for Form Control

- src/Components/Typeahead/Typeahead.purs
- ui-guide/Components/TextFields.purs
- ui-guide/Components/Validation.purs
This PR allows us to thread iprops through to typeaheads, supplying them with an inputId and placeholder (among any other iprops supported by input fields).
> Add arbitrary iprop support to typeaheads.

- src/Core/Utils/Utils.purs
This adds a function `testId` which will create a data attribute with the provided string:
```purescript
testId "myId" -> data-testid=myId
```
With this, we can add a persistent ID for testing purposes.
> Add helper for test attributes

- src/Components/Typeahead/Component.purs
- src/Components/Typeahead/Input.purs
- ui-guide/Utilities/Async.purs
In order to function properly with our application monad in Wildcat, it's necessary that we are less restrictive about what loading functions we pass to and return from the typeahead. This PR changes the typeahead to use the less-restrictive `MonadAff` constraint instead of `Aff` directly.
The only change required of consumers is that they'll have to call `liftAff` on their function if they're trying to use an `Aff` function directly in the typehead. For an example see the `Async` module.
> Switch typeaheads to use MonadAff

- src/Components/Dropdown/Component.purs
- src/Components/Typeahead/Render.purs
- src/Interfaces/Dropdown/Interface.purs
- src/Interfaces/Typeahead/Interface.purs
- src/Interfaces/Utilities.purs
- test/Interop/src/index.js
Adds several new default render implementations for the typeahead (corresponding to our header and toolbar searchable dropdowns), and adds JS usable interfaces for those and the standard dropdown.
> Dropdown Interop

- src/Components/Typeahead/Base.purs
Added ability to change selection for typeaheads via a function, so that the parent doesn't need to hold onto the list of selectable items on the state.
E.g., a typeahead with the item type of `User { id :: UserId | r }`, if the parent has a `UserId` it wishes to use to update the typeahead's selection, instead of needing to hold a copy of the array of available `User`s on state and searching through it for the one with a matching `UserId`, instead it can provide a function to the typeahead component from `Array User -> Maybe User`, and let the typeahead handle the search.
> Added query to set selection by a find/filter function

- bower.json
- src/Interfaces/Typeahead/Interface.purs
- test/Interop/package.json
- test/Interop/src/index.js
Adds the ability to pass an HTML template function as part of the input to the Dropdown Typeahead interface, so that those consuming the component in JavaScript can have some more control over its appearance.
> Support Custom Toggle Rendering in Typeahead Interface

- bower.json
- src/Data/Currency.purs
- test/Main.purs
- test/Test/Currency.purs
We now need `Currency` in https://github.com/citizennet/purescript-lynx/.
We're moving it back out of our private repo to here so we can use it in both without needing to pull in `lynx` right now.
The only difference from the original module is the name. This is the full diff for `src/Data/Currency.purs`:
```diff
1c1
< module CN.Data.Currency where
---
> module Ocelot.Data.Currency where
129d128
<
```
And for `test/Test/Currency.purs`:
```diff
5c5
< import CN.Data.Currency (Cents(..), formatCentsToStrDollars, parseCentsFromDollarStr, parseCentsFromMicroDollars)
---
> import Ocelot.Data.Currency (Cents(..), formatCentsToStrDollars, parseCentsFromDollarStr, parseCentsFromMicroDollars)
```
There's no behavioral changes, just relocating some code. There's not really much to review. Maybe …
> PS-2957 Re-add `Currency`

- src/Components/SearchBar.purs
Opens search bar when setText or Search queries are called if the query is not empty.
> Added code to open search bar if it has a query. Fixes 2/3 items of FBCM-2288

- .circleci/config.yml
- package.json
Speeds up Circle CI build
You can see the compiling step from the [latest test](https://circleci.com/gh/citizennet/purescript-ocelot/871) took 00:16, whereas the [build before](https://circleci.com/gh/citizennet/purescript-ocelot/869) took 13:22 to compile. Quite a bit faster.
> CircleCI speed

- bower.json
- package.json
`purescript-remotedata` was bumped from `4.1.0` to `4.2.0`, which included a major bump to one of its dependencies, which resulted in a cascade of resolution conflicts in bower. I've fixed the version to `4.1.0`, and `bower install` now resolves all packages without issue.
I've also removed the `--silent` flag from the `bower install` script, so that's it's easier for builds that rely on `Ocelot` to see what went wrong.
```sh
rm -rf bower_components
yarn install
yarn run build-all
```
> Fix bower resolution errors

- src/Blocks/NavigationTab.purs
- src/Blocks/TabControl.purs
Adds a more general tab control which takes an `Array IProp` instead of navigation links for it's tab config. This is basically just a copy paste from navigationTabs. I thought to maybe make `navigationTabs`  use this tab implementation, just translating links to iProps, but I wasn't sure if that might introduce some bad coupling in case these two UI controls end up evolving in different ways later on or something. It's certainly an option though if you guys think that seems like a good idea.
> Creates a more general tab control

- src/Components/SearchBar.purs
Fixes the problem of the search bar staying open after the "x" button is clicked. Basically it sums up to adding a `stopPropogation` call in the `Clear` query, which prevents the parent label from getting an `OnClick` event (which re-opens the search bar)
> Fix AS-123 - Close search bar when clear button is clicked

- readme.md
`master` is now a protected branch, so commits directly to it are no longer allowed. We update the wording in our instructions for cutting a new release to reflect that.
Are we okay with adding this extra step to our release process in order to prevent code from accidentally being committed straight to `master`?
> Update release instructions

- src/Data/Currency.purs
Our Currency module was missing some basic functions for converting to and from various types. This meant that consumers were writing their own functions to convert between Cents and other types, which required knowledge of and coupling to the underlying implementation for Cents (Data.BigInt). That meant that if we wanted to switch out that underlying implementation for another, we would cause a breaking change because our consumers then need to update their functions as well.
This PR attempts to offer a better API for Cents so that consumers shouldn't
have to know what's under the hood.
> Improve Currency API

- src/Interfaces/Typeahead/Interface.purs
- test/Interop/src/index.js
Per [PS-3138](https://citizennet.atlassian.net/browse/PS-3138), we need to let QuickSight set images for some of their Typeaheads. They want to differentiate between Facebook and Twitter. We let them tell us which image to display, and we do it.
* Having gone through the implementation of this approach, it doesn't seem right. We have to now manage image sources and resize them. It's not great. I'm making a PR to get a second opinion. I might be overthinking it, but it seems like we might want to instead restrict to just the  icons we support. Would that be better? I think from QS's perspective, there shouldn't be much change.
1. [x] Follow the instructions in for setting up the [interop](https://github.com/citizennet/purescript-ocelot/blob/3041c2085e8d4a6f5c88fa20574ac1c7b15e69f1/src/Inter …
> PS-3138 Allow setting the image next to an item

- package.json
We did #101 so QS could use it. We make a new version so QS can actually refer to the version like it usually does.
* Although we use SemVer, we've been making breaking changes in patch versions. We're still on 0.x.x which means there's no rules, but the reality is that this will break something not just on the JS side. Anyone using `Ocelot.Typeahead.Interface` (transitively) will be broken from this change. I don't particularly care what the version is (if we'd prefer to do 0.16.11, I'll change to that), but I'm defaulting to moving the minor version because of what I laid out above.
* Requesting a review from both Dave and Vance as I think y'all have the most context on our versioning process. Would appreciate if you both could review this one before merging.
> Bump version to 0.17.0

- src/Blocks/Button.purs
This makes the text on dark buttons white, per Product feedback.
<details>
<summary>Old and busted</summary>
</details>
<details>
<summary>New hotness</summary>
</details>
* More discussion in [Slack](https://citizennet.slack.com/archives/C3Q0ATZST/p1578087753001500).
* More information in [JIRA](https://citizennet.atlassian.net/browse/PS-3166).
1. [x] Build the UI: `yarn run build-ui`.
1. [x] Look at the buttons in the browser: `#buttons`.
1. [x] The dark buttons should have white text.
> PS-3166 Use white text for dark buttons

- .k8s/.helmignore
- .k8s/Chart.yaml
- .k8s/README.md
- .k8s/templates/_helpers.tpl
- .k8s/templates/deployment.yaml
- .k8s/templates/ingress.yaml
- .k8s/templates/service.yaml
- Dockerfile
This is more or less copy-pasted from the Lynx repository. A common workflow for some of us it to work on a remote server, where the best way to get browser feedback is to deploy to a k8s cluster managed by helm. Notably we don't really on outside configuration files like in our private repos, since this is a public repo, it should be able to be deployed independently (assuming a compatible deployment environment).
Follow the directions in `.k8s/README.md` from an environment running k8s and helm:
```bash
docker build -t ocelot-local .
helm install --name ocelot .k8s/ --set ingress.host=$(hostname),persistence.path=/home/$USER/src/purescript-ocelot
```
These configs could probably be cleaned up plenty, but wanted to just get this working and move on to the actual task to be worked on.
> Add support for deploying to k8s cluster

- src/Components/TimePicker/Component.purs
There was a bug where the TimePicker (and by usage, DateTimePicker) wasn't rendering the initially provided value. We weren't setting it on the state upon initializing the component. That's fixed now.
It depends on your environment.
If you're developing locally (I haven't tested this method):
If you're developing on EC2:
Before:
After:
> PS-3174: Bugfix: Time components not rendering values

- src/Components/DatePicker/Component.purs
- src/Components/DateTimePicker/Component.purs
- src/Components/TimePicker/Component.purs
- ui-guide/Components/DatePickers.purs
We need the ability to set date components to disabled/read-only. That's exactly what this PR lets us do.
It depends on your environment. 
If you're developing locally (I haven't tested this method): 
If you're developing on EC2:
There is an issue with the hydrated TimePicker not rendering its value, that will be addressed in a separate PR.
> PS-3164: Disabled Dates

- package.json
Bumping the minor version so we can tag a release for the [Date component work](https://github.com/citizennet/purescript-ocelot/compare/v0.18.3...12766fe), which is breaking.
> Bump version to 0.19.0

- src/Components/Tree/Component.purs
The previous syntax only worked for 0.12.x. But since we use `purescript-ocelot` in both 0.12.x and 0.13.x downstream, we need to support syntax for both.
* More discussion on [Slack](https://citizennet.slack.com/archives/C3Q0ATZST/p1578419822023000). Decided not to make CI enforce this stuff.
* Making `purescript-ocelot` work with 0.13.x is non-trivial (the dependencies are all messed up). I've checked it locally, but if you'd like I can add a patch with the things that need to change. Otherwise, trusting CI is probably fine 🤷‍♂.
> Fix syntax to work on both 0.12.x and 0.13.x

- src/Blocks/Header.purs
There was a small layout bug where we were giving the `Ocelot.Block.Header.stickyHeader` block a height of `h-20`, but in usage, we throw `Ocelot.Block.Header.header` inside, which has a height of `h-24`. This caused a discrepancy between the visual height of the header, and the height it took up in the layout (`stickyHeader` gets fixed positioning, so the inner and outer height have to match up so that content doesn't show up underneath the block).
Easiest way to verify is to:
> Fix Header CSS

- css/src/index.css
Seems Tailwind ships its own `.clearfix` class, but it doesn't work in all situations (it only includes a rule for `.clearfix::after`, but we need the same rule for `.clearfix::before` as well). We are using an older version of Tailwind, it's possible this issue is fixed in a more recent version, but it's a lot easier to fix the class ourselves than to upgrade a major version.
Not really an easy way to test.
> Fix `.clearfix` class

- dist/index.html
- dist/main.js
- package.json
When we moved to Spago, we had to update the way we were building and bundling our UI Guide application, because the tools we were using were no longer available. In the process we didn't realize that our tooling no longer bundled for the browser automatically. We install `browserify` to fill that gap, and add the extra step to our build. Since our build has now grown to several steps, we break each out to their own command to make things easier to read, and so we can run each individually, if desired.
If you wish to test this in a local minikube cluster, make sure to follow the directions here: https://github.com/citizennet/purescript-ocelot/tree/master/.k8s/README.md
> Fix bundling

- src/Components/Typeahead/Base.purs
- src/Components/Typeahead/Component.purs
- src/Components/Typeahead/Render.purs
- src/Interfaces/Typeahead/Interface.purs
- ui-guide/Components/Typeaheads.purs
Typeaheads were only allowing statically setting the `disabled` property. We need them to allow setting the property dynamically (when state changes). We added a query to allow setting that property.
* Paired with @davezuch.
> FBCM-3571 Allow disabling Typeaheads dynamically

- ui-guide/Utilities/Async.purs
The `#typeaheads` of `UIGuide` is broken ever since SWAPI changes its domain from `.co` to `.dev`.
- see if examples load up properly
> fix SWAPI urls in UIGuide

- src/Components/Typeahead/Render.purs
This is the expected behavior in older versions (like v0.18) but lost after migrating to v5.
- use the example at the bottom right of the first section (`Typeaheads - Single-Select`) where a user has been selected
- the selection panel should show up
- the old selection should be kept
- the selection panel should show up
- the old selection should be kept
> Bugfix: open selection panel when clicking on the selected or Change button

- src/Components/DatePicker/Component.purs
- src/Components/TimePicker/Component.purs
Before, we only raise `SelectionChanged` when a date/time is selected through the calendar but not through text input which is inconsistent and makes text input less useful. Now we raise `SelectionChanged` whenever `selection` in the `State` is modified.
> Raise SelectionChanged whenever Date/Time selection is updated

- package.json
- src/Components/DatePicker/Component.purs
- src/Components/TimePicker/Component.purs
We postpone parsing and selecting date/time through text input until user presses Enter for confirmation which is reasonable. But this might lead to inconsistent presentation of state between the input field and the calendar.
For example, when user clears the input field and unfocuses it, the selection is expected to be cleared as well, but given current implementation the previous selection persists.
To fix this issue, we force a search when the input field is unfocused just like pressing Enter.
- the selection should be `Sun, Jan 31 2021`
- the selection should be `1:00 PM`
> Trigger Date/Time search on blur

- package.json
- src/Components/SearchBar.purs
- ui-guide/Components/TextFields.purs
When a search bar is configured to keep open, we still want to show the clear button unless the query string is empty.
- you should see the clear (`x`) button
- the query string should be cleared and the search bar should stay open
> AS-991 Show clear button when search bar is configured to keep open

- index.html
As `kejace` reported in issue #140, our document page is down.
Looks like the actual issue is that `example.js` is no longer a build artifact in `dist/` folder so updating `index.html`on branch `gh-pages` should fix this (hopefully).
> Fix gh-pages index.html

- package.json
- src/Blocks/Diagram.purs
- ui-guide/App/Routes.purs
- ui-guide/Components/Diagram.purs
Add `Ocelot.Block.Diagram.percentBar` for visualizing number in percentage.
> AS-1029 Add Percentage Bar Graph block

- package.json
- src/Blocks/Toast.purs
- ui-guide/Components/Modals.purs
When a Toast is raised with a Modal open, it's barely visible behind the dark background of Modal. We fix this issue by lifting Toast to the same `z-index` as Modal.
- you should see an error toast which is not blocked by the dark background
> AS-1073 Bugfix: Toast is blocked by Modal

- package.json
- src/Blocks/Pager.purs
- ui-guide/Components/Table.purs
Add a pager block with new design.
- you should see the pager at the bottom of the table
- that page should be selected (the content of the table won't change)
- previous/next page should be selected
Looks like the old pager relies on `citizennet.css` for class names `cn-pagination` and `pagination` to style properly. Basically the following rules
```css
.cn-pagination {
margin:20px auto;
text-align:right;
max-width:1220px
}
.cn-pagination .pagination {
margin:0 0 0 20px;
vertical-align:middle
}
.cn-pagination .pagination>li>a,
.cn-pagination .pagination>li>span {
border-radius:2px;
background:0 0;
border:none
}
.cn-pagination .pagination>li>a {
color:#3ba0cc
}
.cn-pagination .pagination>li>a:hover {
color:#fff;
background-color:#d4d4d4
}
.cn-pagination .pagination>li.active>a { …
```
> AS-1091 Add pager with new design

- package.json
- src/Blocks/Pager.purs
Should've tested this with `citizennet.css` before merging #149  but there's two minor changes we need to make to the new pager
- use `button` instead of `a` to avoid global style rules on `a`
- remove outline of `button` in `focus` state
> AS-1091 Minor style tweaks to the new pager

- .circleci/config.yml
- Makefile
- src/Interfaces/Typeahead/Interface.purs
- src/Typeahead.purs
- test/Main.purs
- test/Test/Typeahead.purs
- ui-guide/Components/Typeaheads.purs
We've run into a scenario where the filtering and sorting our typeaheads do on results actually gets in the way. The filtering and sorting is very useful for synchronous data, or even asynchronous data when the endpoint doesn't have very good search functionality, but some endpoints will have the context to perform much better search than we can. We've run into one such example with FBCM-4107. When searching for Facebook pages, Facebook can take into account information that isn't returned, like recent name changes, or what the friendly URL is. If the user searches for one of these things but they're not present in the data Facebook returns, we'll end up filtering them out. To address this, we our Typeahead's filtering configurable.
The tests should provide enough confidence, but if you …
> FBCM-4107 Configurable filtering for Typeahead search results

- spago.dhall
- src/Data/IntervalTree.purs
- src/Slider.purs
- src/Slider/Render.purs
- test/Main.purs
- test/Test/Data/IntervalTree.purs
- ui-guide/Components/Diagram.purs
- ui-guide/Components/FormControl.purs
Add slider component
- supports multiple values/thumbs
- allows changing the number of thumbs by query
- has two general modes depending on whether `marks` are specified
- discrete (if `marks` are specified): thumbs can only sit on given set of values
- continuous (if `marks` are left empty): thumbs can slide freely
- able to maintain minimal distance between thumbs if specified
- configurable layout (currently in limited form, see `Ocelot.Slider.Render.Config`)
- customizable render for intervals between thumbs
Features we may add in the future
- clicking on track teleports the closest thumb to the mouse position
- customizable render for marks
- indicator of thumb value when hovering over (especially in continuous setting)
Kind of hard to put everything into words given there are …
> AS-1146 Add Slider Component

- package.json
- src/Slider.purs
When handling `SetThumbCount` query, unless the count (`Int`) is invalid (`< 1`) or no more thumbs can be added (given `minDistance` and `marks`), the thumb values will change and `ValueChanged` output should be raised to parent.
> AS-1161 Raise ValueChanged output when SetThumbCount on Slider

- src/Slider.purs
- ui-guide/Components/FormControl.purs
Improvements to Slider component
* allow replacing thumbs by `ReplaceThumbs` query
* allow disabling the component by setting `disabled: true` from initial `Input` or using `SetDisabled` query
* mouse events over thumbs will be muted
> AS-1164 Add ReplaceThumbs query and disabled prop to Slider

- .circleci/config.yml
Looks like we forgot to update `master` to `main` in `.circleci/config.yml` when migrating the branch so the branch name doesn't line up, which is probably why documentation site rebuild step hasn't been triggered lately.
> fix CircleCI config file

- src/Components/DatePicker/Component.purs
- src/Components/DateTimePicker/Component.purs
- src/Components/TimePicker/Component.purs
- ui-guide/Components/DatePickers.purs
We add a SetDisabled query for the 3 date time related components: DateTimePicker, DatePicker, and TimePicker.
Requesting a review from @davezuch since he's already working in a similar space
Should I bump the version here? Or should we wait for the dropdown change as well and bump the version all at once?
> FBCM-4152 Add Set disabled query for datetime

- src/Components/DatePicker/Component.purs
- src/Components/TimePicker/Component.purs
We stop raising the query we just responded to when we receive it in the `Ocelot.Components.DatePicker.Component` and `Ocelot.Components.TimePicker.Component` components.
- This seems like it's going to fix the issue we had when trying to diagnose https://citizennet.atlassian.net/browse/FBCM-4170, but I'd like another set of eyes on the change. Primarily, I'm not sure I totally understand how this whole `purescript-halogen-select` thing works.
- Since this could potentially cause problems in both the `orders` and `wildcat` repos, requesting a review from both teams.
> FBCM-4170 Don't raise from a query

- package.json
- src/Data/InputAcceptType.purs
- src/FilePicker.purs
- ui-guide/App/Routes.purs
- ui-guide/Components/FilePicker.purs
Add `Ocelot.FilePicker` component which
- allows selecting single/multiple file(s) by drag-and-drop or using browser/OS native file picker
- allows restricting acceptable files by a list of MIME types and/or file extensions
> AS-1264 Add FilePicker Component

- package.json
- src/FilePicker.purs
In Ocelot UIGuide, the label was properly centered but in combination with CN css it's not. Fix it by adding `w-full`.
> AS-1278 Centralize FilePicker label

- package.json
- src/Blocks/Input.purs
The border glitch on Typeahead component happens when the search content cannot be fit into a single line like this
which can be reproduced by going to [UIGuide > Typeahead](https://citizennet.github.io/purescript-ocelot/#typeaheads) and resize the width of the browser window to roughly half screen.
When the container (inputGroup) has "flex" (display: flex), all items will have the same height meaning items of less content will be assigned the same height as the one with the most content. But when the container also has "items-center" (align-items: center) or any item has "self-center" (align-self: center), items' heights are no longer regulated by the container, which cause the glitch that the boundary of search box(`addonLeft`) disconnects with the boundary of button (`addonRight`) when …
> AS-1316 Fix Typeahead border glitch

- src/DatePicker.purs
When selecting a date from previous/next month, the year and month on the calendar are not updated to the year and month of the selected date. Like this
Fixed behavior is
before selecting | after selecting
--- | ---
> AS-1356 Bugfix: Switch year/month when selecting date from previous/next month

- src/DateTimePicker.purs
- src/Slider.purs
- src/TimePicker.purs
- test/Main.purs
- test/Test/TimePicker.purs
- ui-guide/Components/DatePickers.purs
Add an `interval :: Maybe Interval` state to `TimePicker` to control the time points available to select. We could have an `Array` of `Interval`s rather than `Maybe` for finer control but my understanding of AS-1344 doesn't need that granularity so stay with a simpler change for now.
- the selection should be cleared
- there should be a `SelectionChanged: Nothing` output logged
- the available time points should all fall within the interval specified on the slider
- `1:00AM` shouldn't be selected as it's out of range
Note that this PR doesn't merge onto branch `origin/main` but `origin/halogen-v5` which is currently pinned at tag `v0.28.2`, the last commit that's still on `purescript 0.13.8` and `halogen` v5. It's because this subtask under ticket AS-1344 is for OMS and there `purescript` …
> AS-1348 Add Time Range to TimePicker

- src/DatePicker.purs
- src/DateTimePicker.purs
- src/TimePicker.purs
- ui-guide/Components/DatePickers.purs
Add an `interval :: Maybe Interval` state to `DateTimePicker` to control the `Date` and `Time` available to select.
- if `interval = Nothing`, user can freely select `Date` and `Time` in whichever order
- if `interval = Just _`, `TimePicker` is disabled until user make a selection on `Date`
- its Date selection should be cleared
- its Time selection should stay the same (`12:00AM`) with TimePicker disabled
- there should be a `DateTimePicker SelectionChanged: Nothing` output logged
- the available dates should all fall within the interval specified on the slider (from the first day of the beginning year to the last day of the ending year)
- unavailable dates are crossed out
- Time selection should be cleared
- there should be a `DateTimePicker SelectionChanged: Nothing` output logged
- …
> AS-1358 Add DateTime Range to DateTimePicker

- package.json
- src/Components/MultiInput/Component.purs
- src/Typeahead.purs
- ui-guide/Components/Typeaheads.purs
Add a new variant of `Typeahead` (`asyncMultiInput` and `syncMultiInput`) that combines `MultiInput` text field and `Typeahead` fuzzy search dropdown for Tags field.
Talked to Dave on potential solutions. Ideally we want to rebuild `MultiInput` using `Select` logic within `Typeahead`. As an intermediate step, we nest current `MultiInput` inside `Typeahead` and synchronize state between using `Query` and `Output` (both manage a list of selections which has to be in sync).
- typeahead dropdown should show up
- typeahead fuzzy search should narrow available options
- selection should be committed to the list in MultiInput
- open typeahead dropdown and the selected option should be filtered out
- selection should be committed to the list in MultiInput
- open typeahead dropdown and the …
> AS-1452 Add MultiInput variant of Typeahead

- package.json
- src/Typeahead.purs
- ui-guide/Components/Typeaheads.purs
1. items selected on blur through MultiInput are not synchronized to Typeahead Select state
2. items added through `Insertable` cannot be removed from Typeahead Select state
> AS-1510 Bugfix MultiInput variant of Typeahead

- package.json
- src/Typeahead.purs
When clicking to open typeahead dropdown and then closing it on blur, the first option disappears. This is due to another mismatch of item selection behavior between MultiInput text field and Typeahead Select. When search text is empty MultiInput won't commit any item but from #195 Typeahead Select will select the highlighted item (first one in the list). Fix this by checking on blur whether search text is empty or not.
> AS-1521 Bugfix MultiInput Variant of Typeahead #2

- package.json
- packages.dhall
- yarn.lock
This is a non-breaking upgrade so nothing besides bumping the version of `purescript` package and pinning latest package set.
One thing to note is I thought after the new release we can drop the CI step installing `libtinfo` like advertised in [INSTALL.md](https://github.com/purescript/purescript/blob/master/INSTALL.md#the-curses-library) but just tested and it still wouldn't work without explicitly installing `libtinfo` and `libncurses` in the CI environment for some reason.
> AS-1554 Upgrade Purescript to 0.14.3

- package.json
- packages.dhall
- yarn.lock
Upgrade dev dependencies
- `purescript`: from `0.14.2` to `0.14.4`
- `spago`: from `0.15.2` to `0.20.3`
- `package-sets`: from `psc-0.14.2-20210713` to `psc-0.14.4-20210905`
> Upgrade Purescript to 0.14.4

- package.json
- src/Components/Tree/Component.purs
Add `ToggleSingle` query to `Ocelot.Component.Tree` component for (un)checking a single path without re-expanding other selections (`SetSelections` expands all selected paths).
> AS-1787 Add ToggleSingle Query to Tree component

- package.json
- yarn.lock
We install and use `yarn-audit-fix` to find dependencies with security vulnerabilities and update them where possible.
We go from 17 moderate and 14 high severity vulnerabilities, to 12 moderate vulnerabilities.
The default `yarn-audit-fix` command only updates minor semver versions. We might be able to eliminate more vulnerabilities by running `yarn-audit-fix --force` to also update majore semver versions, but there's more risk of upgrading to a dependency that is incompatible with our codebase. Since we've at least eliminated the high severity vulnerabilities, this change should suffice for now.
> Patch vulnerabilities where possible

- package.json
- src/Data/Currency.purs
- test/Test/Data/Currency.purs
The `Ocelot.Data.Currency.formatCentsToStrDollars` and `Ocelot.Data.Currency.parseCentsFromDollarStr` did not work with negative `Cents` values. We fix that by changing their definitions and adding test cases to cover the intended behavior.
Commit-by-commit.
There's no need for manual testing; the automated tests should be enough.
> Fix `Ocelot.Data.Currency` functions not working with negative `Cents` values

- package.json
- src/Components/MultiInput/Component.purs
Currently the MultiInput component has an inner auto-sized input field whose initial width corresponds to that of the placeholder text. This makes is difficult for users to interact with the component, because in order to start typing in, they must necessarily click on the placeholder text, as clicking on anywhere else in the container wouldn't hit the
inner input field. This pull request fixes that behavior.
This is the same PR as #239. We chose to close that and open a new one because CI got stuck.
> FBCM-4913 Expand MultiInput inner input field to fill the whole container

- src/Data/Currency.purs
This instance allows us not only to compare `Cents` values but also to use them in a `Set`, which requires an `Ord` instance.
> FBCM-5115 Add an `Ord` instance for `Cents`

- Makefile
- package-lock.json
- package.json
- src/DateTimePicker.purs
- ui-guide/App/App.purs
- ui-guide/App/Routes.purs
- ui-guide/Blocks/Backdrop.purs
- ui-guide/Blocks/Documentation.purs
- ui-guide/Blocks/Header.purs
- ui-guide/Components/Badge.purs
- ui-guide/Components/Button.purs
- ui-guide/Components/Card.purs
- ui-guide/Components/DatePickers.purs
- ui-guide/Components/Diagram.purs
- ui-guide/Components/Dialogs.purs
- ui-guide/Components/Dropdown.purs
- ui-guide/Components/ExpansionCards.purs
- ui-guide/Components/FilePicker.purs
- ui-guide/Components/FormControl.purs
- ui-guide/Components/Icons.purs
- ui-guide/Components/Modals.purs
- ui-guide/Components/MultiInput.purs
- ui-guide/Components/Tab.purs
- ui-guide/Components/Table.purs
- ui-guide/Components/TextFields.purs
- ui-guide/Components/Tray.purs
- ui-guide/Components/Type.purs
- ui-guide/Components/Typeaheads.purs
- ui-guide/Main.purs
- ui-guide/Utilities/Async.purs
Added `defaultTime` to `DateTimePicker.Input` for auto populating Time with a default value when a Date is selected.
Also made some small improvements in `DateTimePicker` and fixed formatting of `UIGuide`.
- the Time should be automatically set to `1:30 AM`
- the selected Time should not be overridden by the default value (`1:30 AM`)
> API-3333 Support Default Time
