citizennet/purescript-ocelot

src/Blocks/ItemContainer.purs
src/Components/Typeahead/Typeahead.purs
src/Core/Typeahead.purs
src/Core/Utils/Currency.purs
ui-guide/Components/Validation.purs
ui-guide/Utilities/Async.purs

This PR attempts to merge the `develop` branch into the `v1-skin` branch. However, I might have missed something or overwritten with an auto-merge, so please review @whoadave and @crcornwell to see if this looks right.

Merge dev into v1-skin

---

src/HTML/Properties.purs
test/Main.purs

Adds a couple of tests for `appendIProps`. The first makes sure the CSS override algorithm works as expected. The second just provides a baseline profile for anyone trying to improve performance.
`npx pulp test` ;)

Iprops perf

---

readme.md

We're codifying what the current process for releases is so new people know what to do.
Verify that these are the correct steps to performing a release.
I will follow these steps to make a release for the `Currency` work that recently was merged.

PS-2957 Document the release process

---

src/Blocks/Hover.purs

This is my first naive attempt at creating a hover/popup block for ocelot. It's roughly based on tooltip, but I added the ability to anchor it to the "triggering" html. 
If this seems good, I can merge it in, but I'm totally open to changes/suggestions on whatever.

New hover block

---

src/Blocks/Hover.purs
src/Blocks/Popover.purs

This is a sort of card that appears when the triggering html is hovered over. Under the hood, this is just a hover block with some css baked in.
Also -- realized that in the original PR I did for the `hover` block, I pushed it in with the wrong module name (I originally prototyped it within wildcat), so this fixes the component name for that as well
Without any explicit width specified for this block, the "popup" part seems to be constrained to the size of the parent. Still, I don't think we want to make any assumptions about how wide this UI block should be -- setting the width of the internal html we pass in still sizes the card properly so I think this should be ok

Popover block

---

css/src/index.css
package.json
src/Blocks/ToggleButton.purs

This is the official implementation for the button styled radio control -- The `ToggleButton`

New togglebutton control moved over from Wildcat w improvements

---

src/Components/Typeahead/Base.purs

There was one change necessary for getting 0.13.x compiling on this codebase. This is the change.
Requesting a review from multiple people, but one should be enough.

Dedent `where` clause for compatibility with 0.13.x

---

package.json

Bumping the version so we can use this in `orders`.
* See [Slack](https://citizennet.slack.com/archives/C3Q0ATZST/p1578088882013600) for more discussion on what the version should be.

Bump version to 0.18.3

---

package.json

Bumping version to get a release.
Merging through per discussion we had before.

Bump version to 0.19.1

---

package.json

We need the fix from #128 in downstream repos, so we make a release. We made a breaking change, so we bump the version accordingly.

FBCM-3571 Bump version to 0.22.0

---

package.json

We added a new set of social icons, now we want to cut a new release so we can
use them in our downstream applications.

Bump version to 0.23.0

---

package.json

Minor version bump to release the following
* bugfix: ui-guide doesn't load sample data due to domain change of SWAPI
* bugfix: clicking on the selected item or Change button doesn't open panel

Bump version to 0.24.1

---

package.json
src/Components/MultiInput/Component.purs
src/Components/MultiInput/TextWidth.purs
ui-guide/App/Routes.purs
ui-guide/Components/MultiInput.purs

Add `MultiInput` component that functions as a text input but may take multiple values. Currently supports
- automatically adjusted width of input
- removal of existing values
- commit/cancellation of editing existing values
- configurable minimum width for new input
- configurable placeholder texts (primary, secondary)

AS-914 Add MultiInput Component

---

package.json

Bump minor version for adding the Reddit icon.

bump minor version v0.25.1

---

.gitignore
dist/parcel.html
package.json

Add `yarn debug` to mount UIGuide in `parcel` for hot reload.

add parcel for debugging

---

Makefile
package.json
yarn.lock

Running into `parcel` "SemVer" error after checking out `origin/main` and rebuilding everything with `make`. Still not exactly sure why we didn't run into this error earlier but seems to be [a known bug on `parcel-bundler: 1.12.4`](https://stackoverflow.com/questions/66459081/parcel-semver-bug). Downgrading to `1.12.3` solves the problem.
Also adding a `make ui-guide` command for convenience.

Fix parcel SemVer error

---

package.json

* breaking change: consolidate Typeahead modules to `Ocelot.Typeahead`
* new: add Slider component
* improvement: add `Makefile` for build
* improvement: configurable filtering for Typeahead search results

Release 0.26.0

---

package.json

We bump the version in anticipation of our next release.

Bump package.json version to 0.27.0

---

src/DatePicker.purs

AS-1356 Bugfix: Switch year/month when selecting date from previous/next month

---

src/DateTimePicker.purs
src/Slider.purs
src/TimePicker.purs
test/Main.purs
test/Test/TimePicker.purs
ui-guide/Components/DatePickers.purs

AS-1348 Add Time Range to TimePicker

---

src/DatePicker.purs
src/DateTimePicker.purs
src/TimePicker.purs
ui-guide/Components/DatePickers.purs

AS-1358 Add DateTime Range to DateTimePicker

---

src/Clipboard.js
src/Clipboard.purs
ui-guide/Components/Button.purs

Add `Ocelot.Clipboard` component for copying text to clipboard with `Copied` state indicator.

AS-1774 Add `Copy to Clipboard` Button

---

.k8s/README.md
.k8s/templates/deployment.yaml
.k8s/templates/ingress.yaml

We bring our k8s settings and documentation up to date with the current tooling versions we use.
I think I'm the only one who uses this, so I'm going to merge it through.

Update k8s configs

---

.circleci/config.yml
.gitignore
Makefile
dist/parcel.html
package.json
yarn.lock

Upgrade `parcel` to `2.2.1` and remove `parcel-bundler`.

AS-2082 Upgrade `parcel` to v2
